name: gwenv
channels:
- defaults
dependencies:
- python=3.7.*
- cython
- numpy
- ipython
- libspatialindex
- libgdal=2.3.3
- gdal=2.3.3
- pip
- pip:
  - gdal==2.3.3
  - numpydoc
  - sphinx-automodapi
  - sphinxcontrib-bibtex
